### ISSUE TITLE
Maintainability Issue - Merge this if statement with the enclosing one.

### ISSUE THREAD

**Issue by sakshirk** [soen6431group10/robocodeFall2024#3]
Blocks of code inside other blocks, commonly referred to as nested code, can be necessary in some cases but generally increase the complexity of the program. The deeper the nesting, the harder it becomes to follow the flow of the logic, which can lead to confusion and errors. This is why keeping the code structure as flat as possible is recommended. Reducing unnecessary nesting makes the code more readable, easier to debug, and simpler to maintain. Flat code helps developers quickly understand the logic without getting lost in multiple layers of conditions or loops, improving overall code quality and performance.

**Comment by 0matleb2** [comment]
@sakshirk Can you please provide a link to the sonarcloud issue and point to which lines of code in which file represent this issue?
